repos:
  # common checkers
  - hooks:
      - id: end-of-file-fixer
        exclude: .+\.ipy
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-added-large-files
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
  # Disabled
  # Conflict with black
  #    -   repo: https://github.com/PyCQA/isort
  #        rev: 5.10.1
  #        hooks:
  #            -   id: isort
  #                args: ["--profile", "black", "--filter-files"]
  # black is a python formatter
  - hooks:
      - id: black
        language_version: python3
        additional_dependencies: [ 'click<8.1' ]
        args:
          - "-l"
          - "120"
    repo: https://github.com/psf/black
    rev: 22.3.0
  # flake8 is a python code quality analyzer
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
          - "--max-line-length"
          - "120"
        #                additional_dependencies:
        #                    - sphinx-toolbox==2.18.0
        exclude: ^(test|history|DISTRIBUTION|build)
        fail_fast: true
  # commitizen
  - hooks:
      - id: commitizen
        fail_fast: true
        stages:
          - commit-msg
    repo: https://github.com/commitizen-tools/commitizen
    rev: v2.27.0
  # TODO: use tox to handle pytest, mypy and doc build